addSbtPlugin("com.dwijnand"      % "sbt-travisci" % "1.2.0")
addSbtPlugin("com.typesafe.play" % "sbt-plugin"   % "2.8.7")
addSbtPlugin("com.typesafe.sbt"  % "sbt-digest"   % "1.1.4")
addSbtPlugin("com.typesafe.sbt"  % "sbt-gzip"     % "1.0.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-stylus"   % "1.1.0")
addSbtPlugin("com.gilt.sbt"      % "sbt-newrelic" % "0.3.3")
