addSbtPlugin("org.playframework" % "sbt-plugin"   % "3.0.9")
addSbtPlugin("com.github.sbt"    % "sbt-digest"   % "2.1.0")
addSbtPlugin("com.github.sbt"    % "sbt-gzip"     % "2.0.0")
addSbtPlugin("com.github.sbt"    % "sbt-stylus"   % "2.0.1")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.5.5")
